### ISSUE TITLE
在扫描中出现 url列表溢出 UnicodeError: label empty or too long 错误

### ISSUE THREAD

**Issue by ppbibo** [saucer-man/saucerframe#7]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
2019-10-19T09:11:05Z (<ThreadPool at 0x318f33f0b8 5/10/10 hub=<Hub at 0x31f8b22438 thread_ident=0x4484>>, <built-in function getaddrinfo>) failed with UnicodeError

[12554 of 1214235][Elapsed Time: 0:55:41]                                                           Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\encodings\idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

**Comment by saucer-man** [comment]
应该是目标列表中存在不规范的url导致。

参考：https://stackoverflow.com/questions/25103126/label-empty-or-too-long-python-urllib2

**Comment by ppbibo** [comment]
谢谢回复，已解决。
